name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: nicolaschan/publish-nix-image/.github/workflows/build-push.yml@master
    permissions:
      contents: read
      packages: write
    with:
      image: ghcr.io/nicolaschan/sunset-relay
      flake-attr: .#sunset-relay-docker
